### ISSUE TITLE
JDK 17 not compatible with Unreal 5.2 and older

### ISSUE THREAD

**Issue by JasperDeLaat94** [RedpointGames/uet#54]
The Android SDK setup code was recently updated to install JDK 17. Unfortunately, compatibility with JDK 8 was broken somewhere between JDK 11 and 17, causing Gradle build errors for Unreal 5.2 and older.

**Comment by JasperDeLaat94** [comment]
The JDK string is currently hardcoded. I did a quick search in the engine code but found no mention of which specific JDK to use (which explains why it's hardcoded).

I might have an idea for a workaround. It would be to add the JDK version to `IAndroidVersionNumbers` and have `JsonAndroidVersionNumbers` return a value found in the `Android_SDK.json` config file.

Another option would be to implement some kind of `if (UnrealVersion < 5.3)` but that feels quite janky and I don't see you do that anywhere else.

**Comment by JasperDeLaat94** [comment]
Good suggestion. I think it's simple enough to implement, so I will look into this when I have time.

While I agree with you to support the latest SDK's for public Android projects, we make business-to-business VR applications distributed through private MDM methods, which do not have these requirements. Just for context.

**Comment by hach-que** [comment]
A fix should be in #61 if you want to try that out (set `UET_OVERRIDE_JDK_VERSION=11` on your build environment variables).
